### PR TITLE
recursive: introduce SingleLookuper, MultiLookuper, and some shortcuts for known providers

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by amery** [comment]
fixed MultiLookuper.Lookup to avoid returning an error when we do have an answer

**Review by karasz — CHANGES_REQUESTED** [review]
You are using a `c:= new(dns.Client)` in the SingleLookuper which is fine and dandy but by default the dns.Client uses 512b UDP packets which nowadays is quite small. Since you take the effort to create a `dns.Client` and not use the built in functions `dns.Exchange...` I would love to see that used not only for adding `SingleInflight` property but also for increasing the buffer. Probably not to something crazy like the iterator does to 64k but anyways to something bigger than 512. Maybe 1k?

**Comment by amery** [comment]
rebased and introduced `DefaultUDPSize = 1024` to be used with our dns.Client

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
`v0.2.0` tagged

**Pull request merged**
