### PR TITLE
feat: SingleLookuper: made RecursionDesired an option

### PR DESCRIPTION
**Pull request by amery**
Instead of assuming all users of SingleLookuper want recursive requests, we now allow specifying this
if we want this or not.

This way advanced Lookupers, like RootLookuper, can use it

### CODE REVIEW

**Review by karasz — APPROVED** [review]
LGTM although I do not get why an entity that lives in `recursive.go` might ever want to set `recursive` to `false`

**Comment by karasz** [comment]
Maybe in a next commit?

**Comment by amery** [comment]
> Maybe in a next commit?

please check

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
`v0.5.0` tagged due to interface change

**Pull request merged**
