### PR TITLE
adds golangci-lint support and fix errors warnings

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — APPROVED** [review]
LGTM, although 
```diff
-		h.handleExtra(w, r, q)
+		_ = h.handleExtra(w, r, q)
```
feels like cheating

**Comment by amery** [comment]
> LGTM, although 
> ```diff
> -		h.handleExtra(w, r, q)
> +		_ = h.handleExtra(w, r, q)
> ```
> feels like cheating

I do have an error handler on another commit, should I do the PR for that first?

**Comment by amery** [comment]
> LGTM, although
> 
> ```diff
> -		h.handleExtra(w, r, q)
> +		_ = h.handleExtra(w, r, q)
> ```
> 
> feels like cheating

issue better addressed on #64.

**Comment by amery** [comment]
rebased after merging #64

**Pull request merged**
