### PR TITLE
LookupResolver: add missing LookupCNAME implementation

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — APPROVED** [review]
LGTM, but also:
```go
package resolver

import (
"context"
"strings"
"testing"
)

func TestLookupCNAME(t *testing.T) {
tests := []struct {
name  string
cname string
}{
{"www.iana.org.", "icann.org."},
{"www.google.com", "google.com."},
{"google.com", "google.com."},
{"cname-to-txt.go4.org", "test-txt-record.go4.org."},
}
for _, tc := range tests {
l := SystemResolver(true)
s, err := l.LookupCNAME(context.Background(), tc.name)
if err != nil {
t.Fatalf(err.Error())
}
if !strings.HasSuffix(strings.ToLower(s), strings.ToLower(tc.cname)) {
t.Fatalf("not expected cname, want %s, got %s", tc.cname, s)
}
t.Logf("want %s, got %s", tc.cname, s)
}
}
```

**Comment by amery** [comment]
rebased and changed to test using our iterative resolver instead of system's

**Comment by amery** [comment]
fix rebase

**Comment by amery** [comment]
rebased

**Comment by amery** [comment]
rebased and temporarily patches to use `CloudflareLookuper` instead of `RootLookuper` because it explodes as per #21

**Review by karasz — APPROVED** [review]
+1

**Comment by amery** [comment]
`v0.4.7` tagged

**Pull request merged**
