### PR TITLE
exdns: ValidateRestoreReturn() and RestoreReturn() helpers

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — COMMENTED** [review]
I am on the fence with this, it is not wrong, but seems to e like we are patching something in the wrong place. If the response comes from us, then `dns.SetReply(req)` takes care of the message `id` and  all other niceties, if the message is not generated by us, I do not think we should correct it..... as I said, I am on the fence with this.

**Comment by amery** [comment]
> I am on the fence with this, it is not wrong, but seems to e like we are patching something in the wrong place. If the response comes from us, then `dns.SetReply(req)` takes care of the message `id` and  all other niceties, if the message is not generated by us, I do not think we should correct it..... as I said, I am on the fence with this.

It's to be used when we modify the request before passing it over to another exchanger.

**Review by karasz — APPROVED** [review]
ok

**Comment by amery** [comment]
`darvaza.org/resolver@v0.7.19` tagged

**Pull request merged**
