### PR TITLE
exdns: move reusable helpers from tools.go to pkg/exdns/

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — COMMENTED** [review]
Why would you do this? if things are internal to the resolver repo then `tools.go` is a good enough place, if those things can and will be used by other repos then `import "github.com/darvaza-proxy/resolver/pkg/common"` is an ugly import resulting in `common.Decanonize(string)` which has no meaning, what does Decanonize mean when you remove the dns hint? If you really want to move this out than `common` is the bad place to do it, `extradns`, `exdns`, `dnscontrib` or similar are imvho a better place.

**Comment by amery** [comment]
> Why would you do this? if things are internal to the resolver repo then `tools.go` is a good enough place, if those things can and will be used by other repos then `import "github.com/darvaza-proxy/resolver/pkg/common"` is an ugly import resulting in `common.Decanonize(string)` which has no meaning, what does Decanonize mean when you remove the dns hint? If you really want to move this out than `common` is the bad place to do it, `extradns`, `exdns`, `dnscontrib` or similar are imvho a better place.

to be able to use them from `pkg/client` or `pkg/reflect`

**Comment by amery** [comment]
`pkg/common` renamed to `pkg/exdns`

**Review by karasz — CHANGES_REQUESTED** [review]
can you please add this unit test to exdns_test.go?
```go
func TestAsServerAddress(t *testing.T) {
	tests := []struct {
		input string
		ok    bool
	}{
		{"8.8.8.8:53", true},
		{"8.8.8.8", true},
		{"8.8.8.8.9", false},
		{"[2001:4860:4860::8888]:53", true},
		{"2001:4860:4860:0000:0000:0000:0000:0000:8888:53", false},
		{"2001:4860:4860:0000:0000:0000:0000:8888", true},
		{"[2001:4860:4860:0000:0000:0000:0000:8888]:53", true},
	}
	for _, tc := range tests {
		output, err := AsServerAddress(tc.input)

		if err == nil && !tc.ok {
			t.Errorf("%q conversion resulted in %q and error %q", tc.input, output, err)
		} else {
			t.Logf("%q became %q without error", tc.input, output)
		}

	}
}
```

**Comment by amery** [comment]
> can you please add this unit test to exdns_test.go?
> 
> ```go
> func TestAsServerAddress(t *testing.T) {
> 	tests := []struct {
> 		input string
> 		ok    bool
> 	}{
> 		{"8.8.8.8:53", true},
> 		{"8.8.8.8", true},
> 		{"8.8.8.8.9", false},
> 		{"[2001:4860:4860::8888]:53", true},
> 		{"2001:4860:4860:0000:0000:0000:0000:0000:8888:53", false},
> 		{"2001:4860:4860:0000:0000:0000:0000:8888", true},
> 		{"[2001:4860:4860:0000:0000:0000:0000:8888]:53", true},
> 	}
> 	for _, tc := range tests {
> 		output, err := AsServerAddress(tc.input)
> 
> 		if err != nil && tc.ok {
> 			t.Errorf("%q conversion resulted in %q and error %q", tc.input, output, err)
> 		} else {
> 			t.Logf("%q became %q without error", tc.input, output)
> 		}
> 
> 	}
> }
> ```

isn't `2001:4860:4860::8888:53`  a valid IPv6 address?

**Comment by amery** [comment]
@karasz non-failing test added. as `2001:4860:4860::8888:53` is a valid IPv6 address, returning `[2001:4860:4860::8888:53]:53` seems correct .

**Comment by amery** [comment]
reduced test complexity

**Comment by karasz** [comment]
> isn't `2001:4860:4860::8888:53` a valid IPv6 address?
`2001:4860:4860::8888:53` is valid, however `2001:4860:4860:0000:0000:0000:0000:0000:8888:53` is not valid and it is not the same as `2001:4860:4860::8888:53`

**Comment by amery** [comment]
> `2001:4860:4860:0000:0000:0000:0000:0000:8888:53`

@karasz added test for `AsServerAddr("2001:4860:4860:0000:0000:0000:0000:0000:8888:53")`

**Review by karasz — APPROVED** [review]
LGTM, thank you for putting up with my nitpicking

**Comment by amery** [comment]
> LGTM, thank you for putting up with my nitpicking

your nitpicking is essential

**Comment by amery** [comment]
`v0.7.14` tagged

**Pull request merged**
